### ISSUE TITLE
version 9 crashes: ‘Gjs_PanelMenuButton is already registered’

### ISSUE THREAD

**Issue by fcrozat** [wbolster/nothing-to-say#33] opened 2021-02-15 09:05 UTC
After updating to version 9, extension doesn't load anymore:

```
févr. 15 09:29:24 latitude.paris.suse.com gnome-shell[3021]:
JS ERROR: Extension nothing-to-say@extensions.gnome.wouter.bolsterl.ee: Error: Type name Gjs_PanelMenuButton is already registered
_init/GObject.Object._classInit@resource:///org/gnome/gjs/modules/overrides/GObject.js:394:24
registerClass@resource:///org/gnome/gjs/modules/overrides/GObject.js:94:12
@/home/fcrozat/.local/share/gnome-shell/extensions/nothing-to-say@extensions.gnome.wouter.bolsterl.ee/extension.js:97:31
_callExtensionInit@resource:///org/gnome/shell/ui/extensionSystem.js:343:13
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:277:22
_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:490:13
collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17
_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:469:9
_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:499:13
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:530:13
init@resource:///org/gnome/shell/ui/extensionSystem.js:48:9
_initializeUI@resource:///org/gnome/shell/ui/main.js:242:5
start@resource:///org/gnome/shell/ui/main.js:138:5
@<main>:1:31
```

(using GNOME 3.34)

**Comment by wbolster** [comment] 2021-02-15 11:46
can you reproduce this with _only_ this extension enabled?

**Comment by wbolster** [comment] 2021-02-15 11:50
also @fcrozat can you try out this patch and see if that solves the issue? e241294

see also https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/371

another project had a similar issue (https://github.com/win0err/gnome-runcat/issues/4) which was supposedly fixed via a similar change by @win0err (https://github.com/win0err/gnome-runcat/commit/5b52783793f2f7b9d6b340cbcafd1ae367dccb2f)

**Comment by win0err** [comment] 2021-02-15 12:10
@wbolster, GNOME Shell has a nice stable API and backward compatibility! (no)

**Comment by fcrozat** [comment] 2021-02-15 13:07
> also @fcrozat can you try out this patch and see if that solves the issue? [e241294](https://github.com/wbolster/nothing-to-say/commit/e241294611b8485bbb378341d568f1df78cb36a4)
> 
> manually adding that 1 line to `~/.local/share/gnome-shell/extensions/nothing-to- say@extensions.gnome.wouter.bolsterl.ee/extension.js` and re-login should be enough.
> 
> see also https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/371
> 
> another project had a similar issue ([win0err/gnome-runcat#4](https://github.com/win0err/gnome-runcat/issues/4)) which was supposedly fixed via a similar change by @win0err ([win0err/gnome-runcat@5b52783](https://github.com/win0err/gnome-runcat/commit/5b52783793f2f7b9d6b340cbcafd1ae367dccb2f))

I can confirm the fix works fine after manual installation and restarting gnome-shell.

**Comment by wbolster** [comment] 2021-02-15 13:17
@win0err :see_no_evil: :smile:

the whole gnome-shell dev experience is very yolo for me: i hack some js code, then logout+login again, and check `journalctl`. i open my editor again, open the files again, and continue where i left off... not very practical. 🤷

also i run/test against the gnome version on my system, and i wouldn't know a practical way to test other versions...

**Comment by wbolster** [comment] 2021-02-15 13:20
@fcrozat cool, so the fix is all it takes. i'll bump the version and upload a new snapshot to https://extensions.gnome.org/

the underlying problem is likely a conflict with _another_ extension which has the _same_ problem, which likely needs a similar fix. can you identify that offending extension?

```
grep -r PanelMenuButton ~/.local/share/gnome-shell/extensions/
```

…may help.

**Comment by fcrozat** [comment] 2021-02-15 13:36
Strangely, I don't get anything from "grep -ri  PanelMenuButton ~/.local/share/gnome-shell/extensions/ /usr/share/gnome-shell/extensions/" :(

**Comment by wbolster** [comment] 2021-02-15 13:46
🤔 what about `grep -C5 -ri PanelMenu.Button`? maybe then conflicting name (which looks quite generic anyway) is derived automatically if no other name has been specified.

if there are any matches, does the `GObject.registerClass` call include a `GTypeName` argument (like the one added in my previously mentioned commit)?

**Comment by win0err** [comment] 2021-02-15 13:47
> @win0err :see_no_evil: :smile:
> 
> 
> 
> the whole gnome-shell dev experience is very yolo for me: i hack some js code, then logout+login again, and check `journalctl`. i open my editor again, open the files again, and continue where i left off... not very practical. 🤷
> 
> 
> 
> also i run/test against the gnome version on my system, and i wouldn't know a practical way to test other versions...

If you use xorg instead of Wayland, you can just press Alt+F2, type r and press Enter. Logs available in looking glass: Alt+F2 then lg, then Enter. 

I test my shell extension using different Fedora distorts in GNOME Boxes.

**Comment by wbolster** [comment] 2021-02-15 13:54
> If you use xorg instead of Wayland,  […]

xorg? 😕 is that something from prehistoric times? 🙃

> P.S. Useful information:

thanks for the pointers; some of those i didn't see before! 👀

**Comment by fcrozat** [comment] 2021-02-15 17:21
grep -C5 -ri PanelMenu.Button ~/.local/share/gnome-shell/extensions/ /usr/share/gnome-shell/extensions/

/home/fcrozat/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/stylesheet.css-}
/home/fcrozat/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/stylesheet.css-
/home/fcrozat/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/stylesheet.css-
/home/fcrozat/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/stylesheet.css-/* Device Panel Indicator
/home/fcrozat/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/stylesheet.css-
/home/fcrozat/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/stylesheet.css:PanelMenu.Button.gsconnect-device-indicator
/home/fcrozat/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/stylesheet.css-    PopupMenu.PopupMenu
/home/fcrozat/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/stylesheet.css-        PopupMenu.PopupMenuSection.gsconnect-device-menu
/home/fcrozat/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/stylesheet.css-            PopupMenu.PopupSeparatorMenuItem
/home/fcrozat/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/stylesheet.css-                StLabel.gsconnect-device-name
/home/fcrozat/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/stylesheet.css-                StBoxLayout.gsconnect-device-battery
--
/home/fcrozat/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/shell/device.js-/**
/home/fcrozat/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/shell/device.js- * An indicator representing a Device in the Status Area
/home/fcrozat/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/shell/device.js- */
/home/fcrozat/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/shell/device.js-var Indicator = GObject.registerClass({
/home/fcrozat/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/shell/device.js-    GTypeName: 'GSConnectDeviceIndicator'
/home/fcrozat/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/shell/device.js:}, class Indicator extends PanelMenu.Button {
/home/fcrozat/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/shell/device.js-
/home/fcrozat/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/shell/device.js-    _init(params) {
/home/fcrozat/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/shell/device.js-        super._init(0.0, `${params.device.name} Indicator`, false);
/home/fcrozat/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/shell/device.js-        Object.assign(this, params);
/home/fcrozat/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/shell/device.js-
--
/home/fcrozat/.local/share/gnome-shell/extensions/syncthing@gnome.2nv2u.com/extension.js-
/home/fcrozat/.local/share/gnome-shell/extensions/syncthing@gnome.2nv2u.com/extension.js-}
/home/fcrozat/.local/share/gnome-shell/extensions/syncthing@gnome.2nv2u.com/extension.js-ConfigMenuItem = GObject.registerClass({GTypeName: 'ConfigMenuItem'}, ConfigMenuItem)
/home/fcrozat/.local/share/gnome-shell/extensions/syncthing@gnome.2nv2u.com/extension.js-
/home/fcrozat/.local/share/gnome-shell/extensions/syncthing@gnome.2nv2u.com/extension.js-// Syncthing indicator controller
/home/fcrozat/.local/share/gnome-shell/extensions/syncthing@gnome.2nv2u.com/extension.js:class SyncthingIndicator extends PanelMenu.Button {
/home/fcrozat/.local/share/gnome-shell/extensions/syncthing@gnome.2nv2u.com/extension.js-
/home/fcrozat/.local/share/gnome-shell/extensions/syncthing@gnome.2nv2u.com/extension.js-	_init(){
/home/fcrozat/.local/share/gnome-shell/extensions/syncthing@gnome.2nv2u.com/extension.js-		super._init(0.0, "SyncthingIndicator");
/home/fcrozat/.local/share/gnome-shell/extensions/syncthing@gnome.2nv2u.com/extension.js-
/home/fcrozat/.local/share/gnome-shell/extensions/syncthing@gnome.2nv2u.com/extension.js-		this.icon = new SyncthingPanelIcon();
--
/home/fcrozat/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/indicatorStatusIcon.js-
/home/fcrozat/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/indicatorStatusIcon.js-/*
/home/fcrozat/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/indicatorStatusIcon.js- * IndicatorStatusIcon implements an icon in the system status area
/home/fcrozat/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/indicatorStatusIcon.js- */
/home/fcrozat/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/indicatorStatusIcon.js-var IndicatorStatusIcon = GObject.registerClass(
/home/fcrozat/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/indicatorStatusIcon.js:class AppIndicators_IndicatorStatusIcon extends PanelMenu.Button {
/home/fcrozat/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/indicatorStatusIcon.js-    _init(indicator) {
/home/fcrozat/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/indicatorStatusIcon.js-        super._init(0.5, indicator._uniqueId);
/home/fcrozat/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/indicatorStatusIcon.js-        this._indicator = indicator;
/home/fcrozat/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/indicatorStatusIcon.js-
/home/fcrozat/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/indicatorStatusIcon.js-        this._iconBox = new AppIndicator.IconActor(indicator, Panel.PANEL_ICON_SIZE);
--
/home/fcrozat/.local/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com/extension.js-let httpSession = new Soup.SessionAsync();
/home/fcrozat/.local/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com/extension.js-Soup.Session.prototype.add_feature.call(httpSession, new Soup.ProxyResolverDefault());
/home/fcrozat/.local/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com/extension.js-
/home/fcrozat/.local/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com/extension.js-const BingWallpaperIndicator = new Lang.Class({
/home/fcrozat/.local/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com/extension.js-    Name: IndicatorName,
/home/fcrozat/.local/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com/extension.js:    Extends: PanelMenu.Button,
/home/fcrozat/.local/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com/extension.js-
/home/fcrozat/.local/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com/extension.js-    _init: function() {
/home/fcrozat/.local/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com/extension.js-        this.parent(0.0, IndicatorName);
/home/fcrozat/.local/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com/extension.js-
/home/fcrozat/.local/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com/extension.js-        /*
--
/home/fcrozat/.local/share/gnome-shell/extensions/nothing-to-say@extensions.gnome.wouter.bolsterl.ee/extension.js-}
/home/fcrozat/.local/share/gnome-shell/extensions/nothing-to-say@extensions.gnome.wouter.bolsterl.ee/extension.js-Signals.addSignalMethods(Microphone.prototype);
/home/fcrozat/.local/share/gnome-shell/extensions/nothing-to-say@extensions.gnome.wouter.bolsterl.ee/extension.js-
/home/fcrozat/.local/share/gnome-shell/extensions/nothing-to-say@extensions.gnome.wouter.bolsterl.ee/extension.js-const MicrophonePanelButton = GObject.registerClass(
/home/fcrozat/.local/share/gnome-shell/extensions/nothing-to-say@extensions.gnome.wouter.bolsterl.ee/extension.js-  { GTypeName: "MicrophonePanelButton" },
/home/fcrozat/.local/share/gnome-shell/extensions/nothing-to-say@extensions.gnome.wouter.bolsterl.ee/extension.js:  class extends PanelMenu.Button {
/home/fcrozat/.local/share/gnome-shell/extensions/nothing-to-say@extensions.gnome.wouter.bolsterl.ee/extension.js-    _init() {
/home/fcrozat/.local/share/gnome-shell/extensions/nothing-to-say@extensions.gnome.wouter.bolsterl.ee/extension.js-      super._init(0.0, `${Extension.metadata.name} panel indicator`, false);
/home/fcrozat/.local/share/gnome-shell/extensions/nothing-to-say@extensions.gnome.wouter.bolsterl.ee/extension.js-      this.icon = new St.Icon({
/home/fcrozat/.local/share/gnome-shell/extensions/nothing-to-say@extensions.gnome.wouter.bolsterl.ee/extension.js-        icon_name: get_icon_name(false),
/home/fcrozat/.local/share/gnome-shell/extensions/nothing-to-say@extensions.gnome.wouter.bolsterl.ee/extension.js-        style_class: "system-status-icon",
--
/usr/share/gnome-shell/extensions/apps-menu@gnome-shell-extensions.gcampax.github.com/extension.js-    }
/usr/share/gnome-shell/extensions/apps-menu@gnome-shell-extensions.gcampax.github.com/extension.js-}
/usr/share/gnome-shell/extensions/apps-menu@gnome-shell-extensions.gcampax.github.com/extension.js-Signals.addSignalMethods(DesktopTarget.prototype);
/usr/share/gnome-shell/extensions/apps-menu@gnome-shell-extensions.gcampax.github.com/extension.js-
/usr/share/gnome-shell/extensions/apps-menu@gnome-shell-extensions.gcampax.github.com/extension.js-let ApplicationsButton = GObject.registerClass(
/usr/share/gnome-shell/extensions/apps-menu@gnome-shell-extensions.gcampax.github.com/extension.js:class ApplicationsButton extends PanelMenu.Button {
/usr/share/gnome-shell/extensions/apps-menu@gnome-shell-extensions.gcampax.github.com/extension.js-    _init() {
/usr/share/gnome-shell/extensions/apps-menu@gnome-shell-extensions.gcampax.github.com/extension.js-        super._init(1.0, null, false);
/usr/share/gnome-shell/extensions/apps-menu@gnome-shell-extensions.gcampax.github.com/extension.js-
/usr/share/gnome-shell/extensions/apps-menu@gnome-shell-extensions.gcampax.github.com/extension.js-        this.setMenu(new ApplicationsMenu(this, 1.0, St.Side.TOP, this));
/usr/share/gnome-shell/extensions/apps-menu@gnome-shell-extensions.gcampax.github.com/extension.js-        Main.panel.menuManager.addMenu(this.menu);
--
/usr/share/gnome-shell/extensions/places-menu@gnome-shell-extensions.gcampax.github.com/extension.js-    'bookmarks',
/usr/share/gnome-shell/extensions/places-menu@gnome-shell-extensions.gcampax.github.com/extension.js-    'network',
/usr/share/gnome-shell/extensions/places-menu@gnome-shell-extensions.gcampax.github.com/extension.js-];
/usr/share/gnome-shell/extensions/places-menu@gnome-shell-extensions.gcampax.github.com/extension.js-
/usr/share/gnome-shell/extensions/places-menu@gnome-shell-extensions.gcampax.github.com/extension.js-let PlacesMenu = GObject.registerClass(
/usr/share/gnome-shell/extensions/places-menu@gnome-shell-extensions.gcampax.github.com/extension.js:class PlacesMenu extends PanelMenu.Button {
/usr/share/gnome-shell/extensions/places-menu@gnome-shell-extensions.gcampax.github.com/extension.js-    _init() {
/usr/share/gnome-shell/extensions/places-menu@gnome-shell-extensions.gcampax.github.com/extension.js-        super._init(0.0, _('Places'));
/usr/share/gnome-shell/extensions/places-menu@gnome-shell-extensions.gcampax.github.com/extension.js-
/usr/share/gnome-shell/extensions/places-menu@gnome-shell-extensions.gcampax.github.com/extension.js-        let hbox = new St.BoxLayout({ style_class: 'panel-status-menu-box' });
/usr/share/gnome-shell/extensions/places-menu@gnome-shell-extensions.gcampax.github.com/extension.js-        let label = new St.Label({
--
/usr/share/gnome-shell/extensions/window-list@gnome-shell-extensions.gcampax.github.com/workspaceIndicator.js-    }
/usr/share/gnome-shell/extensions/window-list@gnome-shell-extensions.gcampax.github.com/workspaceIndicator.js-});
/usr/share/gnome-shell/extensions/window-list@gnome-shell-extensions.gcampax.github.com/workspaceIndicator.js-
/usr/share/gnome-shell/extensions/window-list@gnome-shell-extensions.gcampax.github.com/workspaceIndicator.js-var WorkspaceIndicator = GObject.registerClass({
/usr/share/gnome-shell/extensions/window-list@gnome-shell-extensions.gcampax.github.com/workspaceIndicator.js-    GTypeName: 'WindowListWorkspaceIndicator',
/usr/share/gnome-shell/extensions/window-list@gnome-shell-extensions.gcampax.github.com/workspaceIndicator.js:}, class WorkspaceIndicator extends PanelMenu.Button {
/usr/share/gnome-shell/extensions/window-list@gnome-shell-extensions.gcampax.github.com/workspaceIndicator.js-    _init() {
/usr/share/gnome-shell/extensions/window-list@gnome-shell-extensions.gcampax.github.com/workspaceIndicator.js-        super._init(0.0, _('Workspace Indicator'), true);
/usr/share/gnome-shell/extensions/window-list@gnome-shell-extensions.gcampax.github.com/workspaceIndicator.js-        this.setMenu(new PopupMenu.PopupMenu(this, 0.0, St.Side.BOTTOM));
/usr/share/gnome-shell/extensions/window-list@gnome-shell-extensions.gcampax.github.com/workspaceIndicator.js-        this.add_style_class_name('window-list-workspace-indicator');
/usr/share/gnome-shell/extensions/window-list@gnome-shell-extensions.gcampax.github.com/workspaceIndicator.js-        this.menu.actor.remove_style_class_name('panel-menu');
--
/usr/share/gnome-shell/extensions/workspace-indicator@gnome-shell-extensions.gcampax.github.com/extension.js-        global.display.disconnect(this._restackedId);
/usr/share/gnome-shell/extensions/workspace-indicator@gnome-shell-extensions.gcampax.github.com/extension.js-    }
/usr/share/gnome-shell/extensions/workspace-indicator@gnome-shell-extensions.gcampax.github.com/extension.js-});
/usr/share/gnome-shell/extensions/workspace-indicator@gnome-shell-extensions.gcampax.github.com/extension.js-
/usr/share/gnome-shell/extensions/workspace-indicator@gnome-shell-extensions.gcampax.github.com/extension.js-let WorkspaceIndicator = GObject.registerClass(
/usr/share/gnome-shell/extensions/workspace-indicator@gnome-shell-extensions.gcampax.github.com/extension.js:class WorkspaceIndicator extends PanelMenu.Button {
/usr/share/gnome-shell/extensions/workspace-indicator@gnome-shell-extensions.gcampax.github.com/extension.js-    _init() {
/usr/share/gnome-shell/extensions/workspace-indicator@gnome-shell-extensions.gcampax.github.com/extension.js-        super._init(0.0, _('Workspace Indicator'));
/usr/share/gnome-shell/extensions/workspace-indicator@gnome-shell-extensions.gcampax.github.com/extension.js-
/usr/share/gnome-shell/extensions/workspace-indicator@gnome-shell-extensions.gcampax.github.com/extension.js-        let container = new St.Widget({
/usr/share/gnome-shell/extensions/workspace-indicator@gnome-shell-extensions.gcampax.github.com/extension.js

**Comment by wbolster** [comment] 2021-02-15 17:37
@fmuellner, since you seem the expert here (e.g. https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/371) :smile: 

:point_up: do you know which one of these may be problematic and may need changes? 🙏

**Comment by wbolster** [comment] 2021-02-20 08:30
the fixed version is now available on extensions.gnome.org

**Closed by wbolster** 2021-02-20 08:30 UTC
Labels: bug, help wanted, needs-info
