### ISSUE TITLE
Error when trying to install, cant enable the extension

### ISSUE THREAD

**Issue by juanriqu** [wbolster/nothing-to-say#48] opened 2022-02-17 17:00 UTC
![image](https://user-images.githubusercontent.com/90963837/154532000-aceea615-b403-4cb0-8b3a-f6175f6cc9c7.png)
I tried rebooting like said in #47 , but nothing works
Tried to install other past versions manually, but does not work.
System: Pop OS 21.10
Gnome 40.4
I can provide more information if its necessary

**Comment by wbolster** [comment] 2022-02-17 17:36
closing this as a duplicate of #47. it has more info and debug tips: https://github.com/wbolster/nothing-to-say/issues/47#issuecomment-1042717417

**Closed by wbolster** 2022-02-17 17:36 UTC
Labels: needs-info
