### ISSUE TITLE
Do not display overlay when re-joining session

### ISSUE THREAD

**Issue by vuntz** [wbolster/nothing-to-say#8] opened 2016-11-02 09:37 UTC
When I come back to the computer and type my password in the screensaver, I can see the overlay window telling me that the microphone is muted.

That's actually pretty annoying as, well, muted is the default for me (I use the PTT mode). I'd like to not have this overlay displayed in that case, or maybe only if the microphone is unmuted?

**Comment by wbolster** [comment] 2016-11-07 13:32
i cannot reproduce. the notification is a response from a gnome-volume-control/pulseaudio event that tells that the mic recording state changed.

do you record audio when your machine is locked to not miss out on any of the office gossip by any chance? ;)

**Comment by vuntz** [comment] 2016-11-08 04:18
Ah, it could be happening because I have mumble running, and the recording state might change when the screen is locked (?). Not sure. Have you tried running an app that records, and then locking the screen?

**Comment by wbolster** [comment] 2016-11-08 09:28
when recording using the gnome sound recorder i do indeed see an osd window telling me that the mic has been activated after i unlock the screen.

there is already a tiny embedded blacklist that currently looks like this:

``` javascript
        if (!id || (id != 'org.gnome.VolumeControl' && id != 'org.PulseAudio.pavucontrol')) {
```

...which i took from the gnome-shell sources. perhaps this list should be extended?

**Comment by wbolster** [comment] 2016-11-16 15:59
closing this bug since microphone disable/enable is controlled by applications that record audio, not by this extension. so if some app starts recording, a notification is actually the intended behaviour.

i am not sure how mumble is supposed to be used, so please open another issue if there is a need to extend the built-in list of blacklisted applications.

**Closed by wbolster** 2016-11-16 15:59 UTC
